# Generated by Django 5.0.6 on 2024-08-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexExpDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=255)),
                ('expiry_date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NSEOptionChainAnalyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=255, null=True)),
                ('index', models.CharField(max_length=255, null=True)),
                ('stock', models.CharField(max_length=255, null=True)),
                ('option_mode', models.CharField(max_length=100, null=True)),
                ('expiry_date', models.CharField(max_length=255, null=True)),
                ('sp_entry', models.FloatField(null=True)),
                ('str_current_time', models.CharField(max_length=255, null=True)),
                ('points', models.FloatField(null=True)),
                ('call_sum', models.FloatField(null=True)),
                ('put_sum', models.FloatField(null=True)),
                ('difference', models.FloatField(null=True)),
                ('call_boundary', models.FloatField(null=True)),
                ('put_boundary', models.FloatField(null=True)),
                ('call_itm', models.FloatField(null=True)),
                ('put_itm', models.FloatField(null=True)),
                ('oi_label', models.CharField(max_length=50, null=True)),
                ('put_call_ratio', models.FloatField(null=True)),
                ('call_exits_label', models.CharField(max_length=10, null=True)),
                ('call_itm_val', models.CharField(max_length=10, null=True)),
                ('put_exits_label', models.CharField(max_length=10, null=True)),
                ('put_itm_val', models.CharField(max_length=10, null=True)),
                ('old_points', models.FloatField(null=True)),
                ('old_points_color', models.CharField(max_length=10, null=True)),
                ('old_call_sum', models.FloatField(null=True)),
                ('old_call_sum_color', models.CharField(max_length=10, null=True)),
                ('old_put_sum', models.FloatField(null=True)),
                ('old_put_sum_color', models.CharField(max_length=10, null=True)),
                ('old_difference', models.FloatField(null=True)),
                ('old_difference_color', models.CharField(max_length=10, null=True)),
                ('old_call_boundary', models.FloatField(null=True)),
                ('old_call_boundary_color', models.CharField(max_length=10, null=True)),
                ('old_put_boundary', models.FloatField(null=True)),
                ('old_put_boundary_color', models.CharField(max_length=10, null=True)),
                ('old_call_itm', models.FloatField(null=True)),
                ('old_call_itm_color', models.CharField(max_length=10, null=True)),
                ('old_put_itm', models.FloatField(null=True)),
                ('old_put_itm_color', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Indices', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=255)),
                ('option_mode', models.CharField(max_length=100)),
                ('index', models.CharField(max_length=255)),
                ('sp_entry', models.FloatField()),
                ('expiry_date', models.CharField(max_length=255, null=True)),
                ('query_datetime', models.DateTimeField()),
            ],
        ),
    ]
