# Generated by Django 5.0.6 on 2024-08-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=255)),
                ('Stock', models.CharField(max_length=255, null=True)),
                ('Consolidating', models.FloatField(null=True)),
                ('Breakout', models.FloatField(null=True)),
                ('LTP', models.FloatField(null=True)),
                ('Volume', models.FloatField(null=True)),
                ('MAsignal', models.CharField(max_length=255, null=True)),
                ('RSI', models.IntegerField(null=True)),
                ('Trend', models.CharField(max_length=255, null=True)),
                ('Pattern', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
