# Generated by Django 5.0.6 on 2024-07-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unisonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockscreen',
            name='Pattern',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
