# Generated by Django 5.0.6 on 2024-08-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unisonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockscreen',
            table='StockScreen',
        ),
    ]
