# Generated by Django 5.0.6 on 2024-08-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unisonapp', '0002_alter_stockscreen_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockscreen',
            name='Breakout',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stockscreen',
            name='Consolidating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stockscreen',
            name='LTP',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stockscreen',
            name='RSI',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stockscreen',
            name='Volume',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
